name: Hourly Screenshot

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:


jobs:
  screenshot:
    runs-on: ubuntu-latest
env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 升级到最新的 Node 24

      - name: Install dependencies
        run: |
          npm install
          # 安装浏览器及其依赖库
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libnss3 libatk-bridge2.0-0 libxkbcommon0 libcomposite1 libasound2
          npx puppeteer browsers install chrome

      - name: Run screenshot script
        run: node screenshot.js

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ github.run_number }}
          path: "*.png"
          if-no-files-found: error
